---
- name: Git clone of pihole
  ansible.builtin.git:
      repo: 'https://github.com/pi-hole/pi-hole.git'
      dest: '{{ git_clone_location }}'

- name: create /etc/pihole folder
  ansible.builtin.file:
      path: /etc/pihole
      state: directory
      mode: '0755'

- name: copy templated setupVars.conf file to /etc/pihole/setupVars.conf
  ansible.builtin.template:
      src: setupVars.conf.j2
      dest: /etc/pihole/setupVars.conf
      mode: '0755'

- name: Run pihole installer
  ansible.builtin.command: bash '{{ git_clone_location }}/pi-hole/automated install/basic-install.sh'

- name: Set pihole password
  ansible.builtin.command: pihole -a -p {{ pihole_password }}
